// <auto-generated />
#nullable enable
using System.Globalization;
using System.Resources;

namespace OnvifManager.Resources;

public static class Strings
{
    private static readonly ResourceManager Rm =
        new("OnvifManager.Resources.Strings", typeof(Strings).Assembly);

    public static CultureInfo? Culture { get; set; }

    public static string AppName => Get(nameof(AppName)) ?? "SeaGull";
    public static string SplashTagline => Get(nameof(SplashTagline)) ?? "ONVIF camera manager";

    private static string? Get(string key) =>
        Rm.GetString(key, Culture ?? CultureInfo.CurrentUICulture);
}
